export const BirdBreedEnum = {
    1: "Canário Belga",
    2: "Canário da Terra",
    3: "Calopsita",
    4: "Periquito Australiano",
    5: "Periquito Inglês",
    6: "Papagaio Verdadeiro",
    7: "Papagaio do Congo",
    8: "Papagaio Eclectus",
    9: "Arara Azul",
    10: "Arara Canindé",
    11: "Arara Vermelha",
    12: "Cacatua Branca",
    13: "Cacatua Rosa",
    14: "Cacatua Alba",
    15: "Amazona Fronte Azul",
    16: "Amazona Aestiva",
    17: "Ring Neck",
    18: "Agapornis Personata",
    19: "Agapornis Fischer",
    20: "Agapornis Roseicollis",
    21: "Manon",
    22: "Mandarim",
    23: "Diamante de Gould",
    24: "Diamante Mandarim",
    25: "Pardal",
    26: "Tico Tico",
    27: "Sabiá Laranjeira",
    28: "Sabiá Branco",
    29: "Coleirinho",
    30: "Trinca Ferro",
    31: "Curió",
    32: "Canário do Reino",
    33: "Azulão",
    34: "Sanhaço Azul",
    35: "Bem Te Vi",
    36: "Rolinha",
    37: "Pomba Doméstica",
    38: "Pomba Asa Branca",
    39: "Codorna Japonesa",
    40: "Codorna Americana",
    41: "Galo Índio",
    42: "Galo Garnizé",
    43: "Galinha D'Angola",
    44: "Frango Caipira",
    45: "Faisão Dourado",
    46: "Faisão Prateado",
    47: "Faisão Real",
    48: "Pato Mandarim",
    49: "Pato Selvagem",
    50: "Marreco de Pompon",
    51: "Marreco Carolina",
    52: "Ganso Chinês",
    53: "Ganso Africano",
    54: "Ganso do Canadá",
    55: "Flamingo Chileno",
    56: "Flamingo Americano",
    57: "Tucano Toco",
    58: "Tucano de Bico Verde",
    59: "Jandaia Coquinho",
    60: "Jandaia Sol",
    61: "Periquito Rei",
    62: "Periquito de Asa Dourada",
    63: "Maracanã Nobre",
    64: "Maracanã Pequena",
    65: "Papagaio Moleiro",
    66: "Papagaio Anão",
    67: "Papagaio do Senegal",
    68: "Papagaio Cinza Africano",
    69: "Lóris Arco Íris",
    70: "Lóris Vermelho",
    71: "Rosela de Pescoço Dourado",
    72: "Rosela de Peito Vermelho",
    73: "Rosela Arco Íris",
    74: "Periquito Barrado",
    75: "Periquito de Bochecha Azul",
    76: "Periquito da Tasmânia",
    77: "Pardal Espanhol",
    78: "Estorninho",
    79: "Melro Preto",
    80: "Canário Harz",
    81: "Canário Gloster",
    82: "Canário Norwich",
    83: "Canário Roller",
    84: "Canário Frisé Parisiense",
    85: "Calafate",
    86: "Bico de Lacre",
    87: "Tucaninho Verde",
    88: "Ararajuba",
    89: "Araçari Castanho",
    90: "Araçari Miudinho",
    91: "Mainá",
    92: "Corvo",
    93: "Corujão Buraqueiro",
    94: "Coruja das Torres",
    95: "Coruja Buraqueira",
    96: "Urubu Rei",
    97: "Carcará",
    98: "Águia Chilena",
    99: "Gavião Peneira",
    100: "Falcon Peregrino",
    101: "Pinguim de Humboldt",
    102: "Pinguim Imperador",
    103: "Pardal Doméstico",
    104: "Pardal Indiano",
    105: "Canário Belga Frisé",
    106: "Agapornis Lilianae",
    107: "Agapornis Taranta",
    108: "Lóris Azul e Amarelo",
    109: "Papagaio Caica",
    110: "Papagaio Cabeça Amarela",
    111: "Arara Severus",
    112: "Arara Vermelha Grande",
    113: "Periquito Príncipe de Gales",
    114: "Periquito Alexandre",
    115: "Calopsita Albina",
    116: "Calopsita Pérola",
    117: "Calopsita Canela",
    118: "Calopsita Cara Branca",
    119: "Canário Satine",
    120: "Canário Vermelho Intenso",
  };
  