export const CatBreedEnum = {
    1: "Abyssinian",
    2: "American Bobtail",
    3: "American Curl",
    4: "American Shorthair",
    5: "American Wirehair",
    6: "Balinese",
    7: "Bengal",
    8: "Birman",
    9: "Bombay",
    10: "British Longhair",
    11: "British Shorthair",
    12: "Burmese",
    13: "Burmilla",
    14: "Chartreux",
    15: "Chausie",
    16: "Colorpoint Shorthair",
    17: "Cornish Rex",
    18: "Cymric",
    19: "Devon Rex",
    20: "Egyptian Mau",
    21: "Exotic Shorthair",
    22: "Havana Brown",
    23: "Himalayan",
    24: "Japanese Bobtail",
    25: "Khao Manee",
    26: "Korat",
    27: "LaPerm",
    28: "Lykoi",
    29: "Maine Coon",
    30: "Manx",
    31: "Munchkin",
    32: "Nebelung",
    33: "Norwegian Forest Cat",
    34: "Ocicat",
    35: "Oriental Longhair",
    36: "Oriental Shorthair",
    37: "Persian",
    38: "Peterbald",
    39: "Pixie Bob",
    40: "Ragamuffin",
    41: "Ragdoll",
    42: "Russian Blue",
    43: "Savannah",
    44: "Scottish Fold",
    45: "Selkirk Rex",
    46: "Siamese",
    47: "Siberian",
    48: "Singapura",
    49: "Snowshoe",
    50: "Somali",
    51: "Sphynx",
    52: "Thai",
    53: "Tonkinese",
    54: "Toyger",
    55: "Turkish Angora",
    56: "Turkish Van",
    // Raças reconhecidas ou populares no Brasil
    57: "Angorá Brasileiro",
    58: "Pelo Curto Brasileiro",
    59: "SRD", // Sem Raça Definida
    // Raças adicionais e raras
    60: "Australian Mist",
    61: "Bambino",
    62: "California Spangled",
    63: "Chantilly Tiffany",
    64: "Cheetoh",
    65: "Dwelf",
    66: "European Burmese",
    67: "German Rex",
    68: "Highlander",
    69: "Kinkalow",
    70: "Kurilian Bobtail",
    71: "Mekong Bobtail",
    72: "Minuet",
    73: "Napoleon",
    74: "Ojos Azules",
    75: "Oriental Bicolor",
    76: "Peterbald Don",
    77: "Raas Cat",
    78: "Serengeti",
    79: "Sokoke",
    80: "Suphalak",
    81: "Thai Lilac",
    82: "Tiffanie",
    83: "Ukrainian Levkoy",
    84: "York Chocolate",
    85: "Arabian Mau",
    86: "Asian Semi Longhair",
    87: "Brazilian Longhair",
    88: "Brazilian Shorthair",
    89: "Japanese Longtail",
    90: "Canadian Hairless",
    91: "New Zealand Rex",
    92: "Polish Cat",
    93: "Cyprus Cat",
    94: "Aegean Cat",
    95: "Turkish Vankedisi",
    96: "Mandarin Cat",
    97: "Asian Smoke",
    98: "British Tipped",
    99: "Oriental Pointed",
    100: "Persian Chinchilla",
  };
  