export const DogBreedEnum = {
  1: "Affenpinscher",
  2: "Airedale Terrier",
  3: "Akita",
  4: "Alaskan Malamute",
  5: "American Bulldog",
  6: "American Pit Bull Terrier",
  7: "American Staffordshire Terrier",
  8: "Australian Cattle Dog",
  9: "Australian Shepherd",
  10: "Basenji",
  11: "Basset Hound",
  12: "Beagle",
  13: "Bearded Collie",
  14: "Belgian Malinois",
  15: "Bernese Mountain Dog",
  16: "Bichon Frise",
  17: "Bloodhound",
  18: "Border Collie",
  19: "Boston Terrier",
  20: "Boxer",
  21: "Brittany Spaniel",
  22: "Bull Terrier",
  23: "Bulldog",
  24: "Bullmastiff",
  25: "Cairn Terrier",
  26: "Cane Corso",
  27: "Cavalier King Charles Spaniel",
  28: "Chihuahua",
  29: "Chow Chow",
  30: "Cocker Spaniel",
  31: "Collie",
  32: "Dachshund",
  33: "Dalmatian",
  34: "Doberman Pinscher",
  35: "Dogue de Bordeaux",
  36: "English Cocker Spaniel",
  37: "English Springer Spaniel",
  38: "French Bulldog",
  39: "German Shepherd",
  40: "German Shorthaired Pointer",
  41: "Golden Retriever",
  42: "Great Dane",
  43: "Great Pyrenees",
  44: "Greyhound",
  45: "Havanese",
  46: "Irish Setter",
  47: "Irish Wolfhound",
  48: "Jack Russell Terrier",
  49: "Japanese Chin",
  50: "Labrador Retriever",
  51: "Lhasa Apso",
  52: "Maltese",
  53: "Mastiff",
  54: "Miniature Pinscher",
  55: "Miniature Schnauzer",
  56: "Newfoundland",
  57: "Old English Sheepdog",
  58: "Papillon",
  59: "Pekingese",
  60: "Pembroke Welsh Corgi",
  61: "Pomeranian",
  62: "Poodle",
  63: "Pug",
  64: "Rhodesian Ridgeback",
  65: "Rottweiler",
  66: "Saint Bernard",
  67: "Saluki",
  68: "Samoyed",
  69: "Scottish Terrier",
  70: "Shar Pei",
  71: "Shetland Sheepdog",
  72: "Shih Tzu",
  73: "Siberian Husky",
  74: "Soft Coated Wheaten Terrier",
  75: "Staffordshire Bull Terrier",
  76: "Vizsla Hungarian",
  77: "Weimaraner",
  78: "Welsh Corgi Cardigan",
  79: "Welsh Terrier",
  80: "West Highland White Terrier",
  81: "Whippet",
  82: "Yorkshire Terrier",
  83: "Fila Brasileiro",
  84: "Bulldog Campeiro",
  85: "Veadeiro Pampeano",
  86: "Terreiro Brasileiro",
  87: "Pastor Branco",
  88: "SRD",
  89: "Dogo Argentino",
  90: "Shiba Inu",
  91: "Bordoodle",
  92: "Cavapoo",
  93: "Goldendoodle",
  94: "Bernedoodle",
  95: "Labradoodle",
  96: "Pit Monster",
  97: "Australian Kelpie",
  98: "Cane Lupo Italiano",
  99: "Kangal",
  100: "Belgian Tervuren",
  101: "Belgian Laekenois",
  102: "American Eskimo Dog",
  103: "Portuguese Water Dog",
  104: "Presa Canario",
  105: "Boerboel",
  106: "Patterdale Terrier",
  107: "Tibetan Mastiff",
  108: "Dutch Shepherd",
  109: "Estrela Mountain Dog",
  110: "Miniature Bull Terrier",
  111: "Biewer Terrier",
  112: "Plott Hound",
  113: "Entlebucher Mountain Dog",
  114: "American Foxhound",
  115: "Norwegian Elkhound",
  116: "Thai Ridgeback",
  117: "Japanese Spitz",
  118: "English Bulldog",
  119: "Italian Greyhound",
  120: "Mudi",
  // Novas raças adicionadas
  121: "Kai Ken",
  122: "Norwich Terrier",
  123: "Norfolk Terrier",
  124: "Chesapeake Bay Retriever",
  125: "American Water Spaniel",
  126: "Leonberger",
  127: "Irish Water Spaniel",
  128: "Curly Coated Retriever",
  129: "Barbet",
  130: "Lagotto Romagnolo",
  131: "Bolognese",
  132: "Tibetan Spaniel",
  133: "Tibetan Terrier",
  134: "Finnish Lapphund",
  135: "Swedish Vallhund",
  136: "Coton de Tulear",
  137: "Spanish Water Dog",
  138: "Peruvian Inca Orchid",
  139: "Xoloitzcuintli",
  140: "Basque Shepherd Dog",
  141: "Carpathian Shepherd",
  142: "Kooikerhondje",
  143: "Beauceron",
  144: "Pyrenean Shepherd",
  145: "Bavarian Mountain Hound",
  146: "Hamiltonstovare",
  147: "Grand Basset Griffon Vendéen",
  148: "Otterhound",
  149: "Norwegian Lundehund",
  150: "Stabyhoun",
  151: "Small Munsterlander",
  152: "Transylvanian Hound",
  153: "Azawakh",
  154: "Sloughi",
  155: "Pharaoh Hound",
  156: "Podenco Ibicenco",
  157: "Podenco Canario",
  158: "Cirneco dell’Etna",
  159: "Czechoslovakian Wolfdog",
  160: "Tamaskan",
  161: "Keeshond",
  162: "Bergamasco Sheepdog",
  163: "Anatolian Shepherd",
  164: "Majorca Shepherd Dog",
  165: "Rafeiro do Alentejo",
  166: "Bulldog Francês Mini",
  167: "Dálmata Long Coat",
  168: "Retriever de Pelo Liso",
  169: "Retriever da Nova Escócia",
  170: "Spitz Alemão",
  171: "Spitz Finlandês",
  172: "Pastor Belga Groenendael",
  173: "Pastor Belga Malinois",
  174: "Pastor Alemão Branco",
  175: "Pastor Australiano Miniatura",
  176: "Pastor de Shetland Mini",
  177: "Pastor Maremano Abruzzese",
  178: "Pastor Polonês das Planícies",
  179: "Pastor Croata",
  180: "Pastor Catalão",
};
