export const ReptileBreedEnum = {
    1: "Iguana Verde",
    2: "Iguana Azul",
    3: "Iguana Rinoceronte",
    4: "Teiú Preto e Branco",
    5: "Teiú Vermelho",
    6: "Teiú Dourado",
    7: "Lagarto Leopardo",
    8: "Lagarto Barbudo",
    9: "Dragão Barbudo",
    10: "Gecko Leopardo",
    11: "Gecko Tokay",
    12: "Gecko de Cauda Gorda",
    13: "Camaleão Pantera",
    14: "Camaleão do Iémen",
    15: "Camaleão de Jackson",
    16: "Camaleão Voador",
    17: "Cágado Tigre d’Água",
    18: "Cágado de Pente",
    19: "Cágado do Pescoço Longo",
    20: "Tartaruga Tigre d’Água",
    21: "Tartaruga de Orelha Vermelha",
    22: "Tartaruga Pés Vermelhos",
    23: "Tartaruga Pés Amarelos",
    24: "Tartaruga de Galápagos",
    25: "Tartaruga Sulcata",
    26: "Tartaruga Leopardo",
    27: "Tartaruga Russa",
    28: "Tartaruga Grega",
    29: "Jabuti Piranga",
    30: "Jabuti Tinga",
    31: "Jabuti Gigante da Amazônia",
    32: "Jacaré do Pantanal",
    33: "Jacaré Açu",
    34: "Jacaré do Papa Amarelo",
    35: "Jacaré Coroa",
    36: "Jacaré de Óculos",
    37: "Cobra do Milho",
    38: "Cobra Real Californiana",
    39: "Cobra Rei",
    40: "Cobra Píton Real",
    41: "Cobra Píton Bola",
    42: "Cobra Píton Reticulada",
    43: "Cobra Píton Birmana",
    44: "Cobra Jiboia",
    45: "Cobra Sucuri Verde",
    46: "Cobra Sucuri Amarela",
    47: "Cobra Coral Verdadeira",
    48: "Cobra Falsa Coral",
    49: "Cobra Verde Arbórea",
    50: "Cobra Papagaio",
    51: "Cobra D’Água",
    52: "Cobra Cega",
    53: "Cobra Nariguda",
    54: "Serpente do Leite",
    55: "Serpente de Areia do Saara",
    56: "Serpente Verde Asiática",
    57: "Serpente do Milharal Albina",
    58: "Serpente do Milharal Snow",
    59: "Serpente do Milharal Blood Red",
    60: "Serpente Rei Mexicana",
    61: "Serpente Rei da Flórida",
    62: "Serpente Rei do Deserto",
    63: "Serpente Cobra Verde Brasileira",
    64: "Lagartixa Doméstica",
    65: "Lagartixa Tropical",
    66: "Calango Verde",
    67: "Calango do Cerrado",
    68: "Calango do Nordeste",
    69: "Camaleão Africano",
    70: "Camaleão Pigmeu",
    71: "Dragão de Água Chinês",
    72: "Dragão de Água Vietnamita",
    73: "Dragão do Deserto",
    74: "Lagarto Monitor de Savana",
    75: "Lagarto Monitor de Água",
    76: "Lagarto Monitor Preto",
    77: "Lagarto Monitor Gigante",
    78: "Lagarto Monitor da Malásia",
    79: "Anolis Verde",
    80: "Anolis Marrom",
    81: "Skink de Fogo",
    82: "Skink de Língua Azul",
    83: "Skink de Cauda Vermelha",
    84: "Skink de Cauda Azul",
    85: "Jacarezinho da Amazônia",
    86: "Jacaré Papo Amarelo",
    87: "Jacaré de Papo Roxo",
    88: "Tartaruga Marinha Verde",
    89: "Tartaruga Marinha de Pente",
    90: "Tartaruga Marinha Oliva",
    91: "Tartaruga Marinha Cabeçuda",
    92: "Tartaruga Marinha Couro",
    93: "Tartaruga Ninja de Aquário",
    94: "Tartaruga Pintada",
    95: "Tartaruga Aquática Oriental",
    96: "Jabuti Africano Sulcata",
    97: "Jabuti Leopardo",
    98: "Jabuti Russo",
    99: "Jabuti Indiano Estrelado",
    100: "Jabuti de Aldabra",
  };
  