export const RodentBreedEnum = {
    1: "Hamster Sírio",
    2: "Hamster Anão Russo",
    3: "Hamster Roborovski",
    4: "Hamster Chinês",
    5: "Hamster de Campbell",
    6: "Porquinho da Índia",
    7: "Cobaia Peruana",
    8: "Cobaia Abissínia",
    9: "Cobaia Americana",
    10: "Cobaia Coronet",
    11: "Cobaia Sheltie",
    12: "Cobaia Texel",
    13: "Cobaia Alpaca",
    14: "Rato Doméstico",
    15: "Rato Albino",
    16: "Rato Dumbo",
    17: "Rato Rex",
    18: "Rato Manx",
    19: "Rato de Laboratório",
    20: "Camundongo Doméstico",
    21: "Camundongo de Fantasia",
    22: "Camundongo de Cauda Curta",
    23: "Chinchila Padrão Cinza",
    24: "Chinchila Preta",
    25: "Chinchila Bege",
    26: "Chinchila Branca",
    27: "Chinchila Safira",
    28: "Chinchila Violeta",
    29: "Degus Chileno",
    30: "Esquilo da Mongólia",
    31: "Esquilo do Japão",
    32: "Esquilo da Sibéria",
    33: "Gerbil Mongol",
    34: "Gerbil Persa",
    35: "Gerbil do Saara",
    36: "Gerbil Egípcio",
    37: "Capivara",
    38: "Cutia",
    39: "Paca",
    40: "Preá Brasileiro",
    41: "Ratão do Banhado",
    42: "Ouriço Pigmeu Africano",
    43: "Ouriço Europeu",
    44: "Ouriço de Ventre Branco",
    45: "Esquilo Voador do Sul",
    46: "Esquilo Voador do Norte",
    47: "Esquilo de Finlândia",
    48: "Porco Espinho Africano",
    49: "Porco Espinho Indiano",
    50: "Porco Espinho Brasileiro",
    51: "Rato do Bambu",
    52: "Rato do Campo",
    53: "Rato Selvagem",
    54: "Rato do Deserto",
    55: "Camundongo Pigmeu Africano",
    56: "Camundongo Saltador",
    57: "Camundongo Selvagem Europeu",
    58: "Camundongo do Mato",
    59: "Gerbil Anão",
    60: "Gerbil Gigante",
    61: "Gerbil de Orelhas Pretas",
    62: "Chinchila Royal Persa",
    63: "Chinchila Gigante",
    64: "Hamster Albino",
    65: "Hamster Panda",
    66: "Hamster Dourado",
    67: "Hamster Cinza",
    68: "Hamster Marrom",
    69: "Hamster Branco",
    70: "Rato Preto",
    71: "Rato Cinza Claro",
    72: "Rato Marrom",
    73: "Rato Azul Russo",
    74: "Cobaia Satin",
    75: "Cobaia Rex",
    76: "Cobaia Skinny",
    77: "Cobaia Baldwin",
    78: "Gerbil Albino",
    79: "Gerbil Creme",
    80: "Gerbil Preto",
    81: "Gerbil Dourado",
    82: "Gerbil Cinza",
    83: "Esquilo de Cauda Vermelha",
    84: "Esquilo de Cauda Dourada",
    85: "Esquilo do Cerrado",
    86: "Capivara Amazônica",
    87: "Paca Gigante",
    88: "Cutia Vermelha",
    89: "Cutia Preta",
    90: "Preá do Pantanal",
    91: "Ratão do Rio",
    92: "Porco Espinho do Mato",
    93: "Rato Albino Doméstico",
    94: "Rato de Estimação",
    95: "Rato Selvagem Brasileiro",
    96: "Hamster Branco de Inverno",
    97: "Hamster Roborovski Albino",
    98: "Hamster de Orelhas Negras",
    99: "Hamster Anão Siberiano",
    100: "Roedor Não Identificado",
  };
  