export enum ErrorEnum {
    USER_CREATE_ERROR = 'E-0000',
    USER_NOT_FOUND = 'E-0001',
    USER_ALREADY_EXISTS = 'E-0002',
    USER_NOT_AUTHORIZED = 'E-0003',
    USER_INVALID_CREDENTIALS = 'E-0004',
}